import {
  Book,
  BookCategory,
  Author,
  Testimonial,
  Interview,
  BrieflyNotedBook,
  FrameworkRanking,
} from "../types/book";

export const bookCategories: BookCategory[] = [
  {
    id: "1",
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    description:
      "Cutting-edge insights on artificial intelligence and ML applications",
    icon: "🤖",
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "Leadership",
    slug: "leadership",
    description: "Strategic leadership in the digital transformation era",
    icon: "👥",
    color: "bg-purple-500",
  },
  {
    id: "3",
    name: "Business Transformation",
    slug: "business-transformation",
    description: "Comprehensive guides to organizational change",
    icon: "🔄",
    color: "bg-green-500",
  },
  {
    id: "4",
    name: "Strategy",
    slug: "strategy",
    description: "Digital strategy frameworks and methodologies",
    icon: "🎯",
    color: "bg-orange-500",
  },
  {
    id: "5",
    name: "Innovation",
    slug: "innovation",
    description: "Driving innovation in digital-first organizations",
    icon: "💡",
    color: "bg-yellow-500",
  },
  {
    id: "6",
    name: "Data & Analytics",
    slug: "data-analytics",
    description: "Leveraging data for competitive advantage",
    icon: "📊",
    color: "bg-teal-500",
  },
];

// Featured Books for 2025-2026 Digital Transformation Reviews
const featuredBooks: Book[] = [
  {
    id: "6xd-six-digital-perspectives",
    title: "6xD: The Six Digital Perspectives",
    author: "Dr. Stephane Niango",
    description:
      "A provocative and ambitious blueprint for the evolution of traditional businesses into Digital Cognitive Organizations (DCOs). Challenges conventional wisdom about digital transformation barriers.",
    shortDescription: "Blueprint for Digital Cognitive Organizations",
    perspectiveOn: "Cognitive Architecture",
    coverImage: "/Volume 00 (4).png",
    rating: 4.8,
    reviewCount: 287,
    category: bookCategories[2],
    tags: [
      "Digital Transformation",
      "AI",
      "Cognitive Architecture",
      "6xD Framework",
    ],
    isbn: "978-1234567890",
    publishDate: "2025-01-15",
    pageCount: 385,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Digital Cognitive Organizations and 6xD Framework",
    reviewSummary:
      "Ambitious blueprint for transforming businesses into Digital Cognitive Organizations",
    transformationImpactScore: 9.2,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.9,
    sixDDimensions: [
      "D1: Digital Economy",
      "D2: Platforms",
      "D3: Digital & AI",
      "D4: Operations & Execution",
      "D5: People & Culture",
      "D6: Acceleration",
    ],
  },
  {
    id: "2",
    title: "AI Leadership in the Digital Age",
    author: "A. Pauceanu",
    description:
      "With a focus on aligning business strategy with AI capabilities, this book provides a bridge between technical knowledge and practical business applications.",
    shortDescription: "Bridging tech knowledge with business use",
    perspectiveOn: "AI Strategy",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.7,
    reviewCount: 289,
    category: bookCategories[0],
    tags: ["AI", "Business Strategy", "Integration", "2026"],
    isbn: "978-1234567891",
    publishDate: "2026-02-01",
    pageCount: 312,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Bridging tech knowledge with business use",
    reviewSummary:
      "Essential guide for aligning business strategy with AI capabilities",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D3: Digital & AI", "D2: Platforms"],
  },
  {
    id: "3",
    title: "Strategic Digital Leadership",
    author: "E. Iveroth",
    description:
      "Iveroth's book is a critical resource for leaders, offering a comprehensive guide on managing governance, control, and execution at scale during digital transformation.",
    shortDescription: "Governance and control in organizations",
    perspectiveOn: "Execution",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.8,
    reviewCount: 256,
    category: bookCategories[1],
    tags: ["Leadership", "Governance", "Execution", "Scale"],
    isbn: "978-1234567892",
    publishDate: "2025-03-20",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Governance and control in organizations",
    reviewSummary:
      "Comprehensive guide for managing governance and execution at scale",
    transformationImpactScore: 8.2,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D5: People & Culture", "D4: Operations & Execution"],
  },
  {
    id: "4",
    title: "Data-Driven Decision Making",
    author: "Ray Kurzweil",
    description:
      "A fascinating exploration of the future of AI and its convergence with humanity, offering a bold vision for the future of digital transformation.",
    shortDescription: "Predictions on human-AI merging",
    perspectiveOn: "Future Vision",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.6,
    reviewCount: 423,
    category: bookCategories[0],
    tags: ["AI", "Future", "Singularity", "Innovation"],
    isbn: "978-1234567893",
    publishDate: "2025-06-10",
    pageCount: 456,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Predictions on human-AI merging",
    reviewSummary: "Bold vision for the future of AI and humanity convergence",
    transformationImpactScore: 7.2,
    actionabilityScore: 3.8,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D3: Digital & AI", "D6: Acceleration"],
  },
  {
    id: "5",
    title: "Innovation Frameworks for Digital Transformation",
    author: "Ethan Mollick",
    description:
      "This groundbreaking book addresses the ethical challenges and opportunities of human-AI collaboration, offering frameworks to navigate the evolving dynamics of AI ethics in business.",
    shortDescription: "Human-AI collaboration and dynamics",
    perspectiveOn: "AI Ethics",
    coverImage: "/book cover/innovation-frameworks.svg",
    rating: 4.8,
    reviewCount: 198,
    category: bookCategories[0],
    tags: ["AI Ethics", "Collaboration", "Human-AI", "Frameworks"],
    isbn: "978-1234567894",
    publishDate: "2025-04-15",
    pageCount: 324,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Human-AI collaboration and dynamics",
    reviewSummary:
      "Groundbreaking exploration of ethical human-AI collaboration",
    transformationImpactScore: 8.0,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D3: Digital & AI", "D5: People & Culture"],
  },
  {
    id: "6",
    title: "The Future of Work in Digital Economy",
    author: "Karen Hao",
    description:
      "An in-depth exploration of OpenAI's journey and its impact on the broader tech ecosystem, this book is a must-read for anyone interested in the innovation behind AI transformation.",
    shortDescription: "Inside story of OpenAI and Sam Altman",
    perspectiveOn: "Innovation",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.7,
    reviewCount: 267,
    category: bookCategories[4],
    tags: ["OpenAI", "Innovation", "Tech Ecosystem", "AI History"],
    isbn: "978-1234567895",
    publishDate: "2025-05-20",
    pageCount: 378,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Inside story of OpenAI and Sam Altman",
    reviewSummary: "In-depth exploration of OpenAI's transformative journey",
    transformationImpactScore: 7.5,
    actionabilityScore: 3.9,
    strategicDepthScore: 4.2,
    sixDDimensions: ["D3: Digital & AI", "D1: Digital Economy"],
  },
  {
    id: "7",
    title: "How AI Ate the World",
    author: "Chris Stokel-Walker",
    description:
      "Stokel-Walker's book provides a unique perspective on AI's transformation of industries. It covers case studies of how AI is reshaping traditional business operations.",
    shortDescription: "AI's impact on industry operations",
    perspectiveOn: "Industry Shifts",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.5,
    reviewCount: 189,
    category: bookCategories[2],
    tags: [
      "Industry Transformation",
      "Case Studies",
      "AI Impact",
      "Operations",
    ],
    isbn: "978-1234567896",
    publishDate: "2025-07-12",
    pageCount: 342,
    format: ["paperback", "ebook"],
    availability: "available",
    keyFocusArea: "AI's impact on industry operations",
    reviewSummary: "Unique perspective on AI's transformation of industries",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.1,
    strategicDepthScore: 4.0,
    sixDDimensions: ["D3: Digital & AI", "D4: Operations & Execution"],
  },
  {
    id: "8",
    title: "Digital Resilience & Cybersecurity",
    author: "T. Singh",
    description:
      "This book tackles the importance of digital resilience in supply chains, offering strategies for organizations to safeguard against cybersecurity threats during digital transformation.",
    shortDescription: "Cybersecurity in supply chains",
    perspectiveOn: "Resilience",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.6,
    reviewCount: 234,
    category: bookCategories[3],
    tags: ["Cybersecurity", "Resilience", "Supply Chain", "Risk Management"],
    isbn: "978-1234567897",
    publishDate: "2025-08-30",
    pageCount: 289,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Cybersecurity in supply chains",
    reviewSummary:
      "Essential strategies for digital resilience and cybersecurity",
    transformationImpactScore: 8.1,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.1,
    sixDDimensions: ["D2: Platforms", "D4: Operations & Execution"],
  },
  {
    id: "9",
    title: "Quantum Computing for Business Leaders",
    author: "M. Chen",
    description:
      "A comprehensive guide to understanding quantum computing's potential impact on business strategy and digital transformation initiatives.",
    shortDescription: "Quantum computing's business applications",
    perspectiveOn: "Emerging Tech",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.3,
    reviewCount: 156,
    category: bookCategories[0],
    tags: ["Quantum Computing", "Emerging Tech", "Business Strategy"],
    isbn: "978-1234567898",
    publishDate: "2025-09-15",
    pageCount: 267,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Quantum computing's business applications",
    reviewSummary: "Strategic guide to quantum computing for business leaders",
    transformationImpactScore: 6.8,
    actionabilityScore: 3.5,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D3: Digital & AI", "D6: Acceleration"],
  },
  {
    id: "10",
    title: "Spatial Commerce Revolution",
    author: "L. Rodriguez",
    description:
      "Exploring the intersection of AR/VR, spatial computing, and commerce to create immersive customer experiences.",
    shortDescription: "AR/VR in commerce and customer experience",
    perspectiveOn: "Spatial Tech",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.4,
    reviewCount: 203,
    category: bookCategories[4],
    tags: ["AR/VR", "Spatial Computing", "Commerce", "Customer Experience"],
    isbn: "978-1234567899",
    publishDate: "2025-10-20",
    pageCount: 298,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "AR/VR in commerce and customer experience",
    reviewSummary: "Revolutionary approach to spatial commerce experiences",
    transformationImpactScore: 7.1,
    actionabilityScore: 4.0,
    strategicDepthScore: 3.9,
    sixDDimensions: ["D1: Digital Economy", "D3: Digital & AI"],
  },
];

// Mock data for different sections - organized by 6xD dimensions
const frontierBooks: Book[] = [
  // Digital Economy (Business Models & Value Networks)
  {
    id: "digital-transformation-playbook",
    title: "The Digital Transformation Playbook",
    author: "David L. Rogers",
    description:
      "Rethinking strategic assumptions in five domains: customers, competition, data, innovation, and value. A foundational guide for digital business model transformation.",
    shortDescription: "Strategic frameworks for digital business models",
    perspectiveOn: "Digital Strategy",
    coverImage:
      "/Digital E/The Digital Transformation Playbook - Google Books/imgi_3_default.jpg",
    rating: 4.8,
    reviewCount: 342,
    category: bookCategories[3], // Strategy
    tags: [
      "Business Models",
      "Digital Strategy",
      "Value Networks",
      "Innovation",
    ],
    isbn: "978-1234567901",
    publishDate: "2025-03-15",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Digital business model transformation",
    reviewSummary:
      "Essential guide for rethinking business strategy in digital age",
    transformationImpactScore: 9.1,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D1: Digital Economy"],
  },
  {
    id: "economics-of-data-analytics",
    title: "The Economics of Data, Analytics, and Digital Transformation",
    author: "Bill Schmarzo",
    description:
      "Treating data as a renewable economic asset to drive tangible business value. Comprehensive framework for data-driven value creation.",
    shortDescription: "Data as economic asset for business value",
    perspectiveOn: "Data Economics",
    coverImage:
      "/Digital E/The Economics of Data, Analytics, and Digital Transformation_ The theorems ... - Bill Schmarzo, Dr. Kirk Borne - Google Books/imgi_4_content.jpg",
    rating: 4.6,
    reviewCount: 234,
    category: bookCategories[5], // Data & Analytics
    tags: ["Data Economics", "Analytics", "Business Value", "Digital Assets"],
    isbn: "978-1234567902",
    publishDate: "2025-06-20",
    pageCount: 324,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Data-driven economic value creation",
    reviewSummary: "Strategic guide to monetizing data assets",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D1: Digital Economy"],
  },
  {
    id: "driving-digital-strategy",
    title: "Driving Digital Strategy: A Guide to Reimagining Your Business",
    author: "Sunil Gupta",
    description:
      "Case studies on how legacy companies like the New York Times and Best Buy reimagined their business models for the digital age.",
    shortDescription: "Legacy company digital transformation case studies",
    perspectiveOn: "Digital Business Models",
    coverImage:
      "/10 book covers/9 Must-Read Digital Transformation Books in 2025 _ Informa TechTarget/imgi_8_Driving_Digital_Strategy_amazon.png",
    rating: 4.7,
    reviewCount: 189,
    category: bookCategories[3], // Strategy
    tags: [
      "Digital Strategy",
      "Business Models",
      "Case Studies",
      "Legacy Transformation",
    ],
    isbn: "978-1234567903",
    publishDate: "2025-04-10",
    pageCount: 267,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Digital business model reimagination",
    reviewSummary:
      "Practical case studies of successful digital transformations",
    transformationImpactScore: 8.9,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D1: Digital Economy"],
  },
  {
    id: "demand-driven-business-strategy",
    title:
      "Demand-Driven Business Strategy: Digital Transformation and Business Model Innovation",
    author: "Alireza Lari",
    description:
      "Aligning digital transformation with innovative business models to meet evolving market demands and customer expectations.",
    shortDescription: "Demand-driven digital business innovation",
    perspectiveOn: "Market-Driven Strategy",
    coverImage:
      "/Digital E/Amazon.com_ Demand-Driven Business Strategy (Business and Digital Transformation)_ 9781032127668_ Molenaar, Cor_ Books/imgi_58_819sO9B8LxL._SL1500_.jpg",
    rating: 4.5,
    reviewCount: 156,
    category: bookCategories[3], // Strategy
    tags: [
      "Demand-Driven",
      "Business Innovation",
      "Market Strategy",
      "Customer-Centric",
    ],
    isbn: "978-1234567904",
    publishDate: "2025-08-15",
    pageCount: 289,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Market-driven business model innovation",
    reviewSummary: "Strategic framework for demand-driven transformation",
    transformationImpactScore: 8.3,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D1: Digital Economy"],
  },

  // Digital Cognitive Organization (AI & Cognitive Systems)
  {
    id: "digital-transformation-subconscious-minds",
    title:
      "Digital Transformation Shaping the Subconscious Minds of Organizations",
    author: "Werner Leodolter",
    description:
      "How AI, robotics, and sensors create 'hybrid intelligences' that improve organizational decision-making and cognitive capabilities.",
    shortDescription: "AI-driven organizational cognitive transformation",
    perspectiveOn: "Cognitive AI",
    coverImage:
      "/DCO/Digital Transformation Shaping the Subconscious Minds of Organizations - Google Books/imgi_3_default.jpg",
    rating: 4.6,
    reviewCount: 178,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "Cognitive AI",
      "Organizational Intelligence",
      "Hybrid Intelligence",
      "Decision-Making",
    ],
    isbn: "978-1234567905",
    publishDate: "2025-09-20",
    pageCount: 312,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Cognitive organizational transformation",
    reviewSummary: "Exploration of AI-driven organizational intelligence",
    transformationImpactScore: 8.8,
    actionabilityScore: 4.2,
    strategicDepthScore: 4.7,
    sixDDimensions: ["D2: Digital Cognitive Organization"],
  },
  {
    id: "integrating-business-ai",
    title:
      "Integrating Business and AI: Developing, Selling and Implementing AI in Business",
    author: "B. S. S. S. Rao",
    description:
      "A practical guide for leaders on the lifecycle of AI implementation within a corporate structure, from development to deployment.",
    shortDescription: "Practical AI implementation lifecycle guide",
    perspectiveOn: "AI Implementation",
    coverImage:
      "/DCO/Cognitive Organizations_ Leveraging the Full Power of Generative AI and Intelligent Agents eBook _ Corrêa, Kenneth_ Amazon.com.au_ Kindle Store/imgi_34_91fGGWBMzSL._SL1500_.jpg",
    rating: 4.4,
    reviewCount: 203,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "AI Implementation",
      "Business Integration",
      "AI Lifecycle",
      "Corporate AI",
    ],
    isbn: "978-1234567906",
    publishDate: "2025-07-25",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "AI business integration lifecycle",
    reviewSummary: "Comprehensive guide to AI implementation in business",
    transformationImpactScore: 8.5,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D2: Digital Cognitive Organization"],
  },
  {
    id: "digital-hr-critical-management",
    title:
      "Digital HR: A Critical Management Approach to the Digitalization of Organizations",
    author: "Amelia Manuti, Pasquale Davide de Palma",
    description:
      "Managing the shift toward cognitive intelligence and redefining the human role in a digital labor market.",
    shortDescription: "HR transformation in cognitive organizations",
    perspectiveOn: "Digital HR",
    coverImage:
      "/DCO/Cognitive Kin_ How to Work, Win, and Make Meaning with Agentic AI_ Kolb, Christophe, Rosen, Jan_ 9781646872121_ Amazon.com_ Books/imgi_91_81Uijf9x14L._SL1500_.jpg",
    rating: 4.5,
    reviewCount: 167,
    category: bookCategories[1], // Leadership
    tags: [
      "Digital HR",
      "Cognitive Intelligence",
      "Human Resources",
      "Digital Labor",
    ],
    isbn: "978-1234567907",
    publishDate: "2025-10-30",
    pageCount: 276,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "HR transformation for cognitive organizations",
    reviewSummary: "Critical approach to HR in digital transformation",
    transformationImpactScore: 8.2,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.2,
    sixDDimensions: ["D2: Digital Cognitive Organization"],
  },
  {
    id: "sizing-prize-ai-future",
    title: "Sizing the Prize: The Future Economic Impact of AI",
    author: "PwC Research Team",
    description:
      "Analyzing the large-scale economic shifts driven by AI automation and smart decision-making systems across industries.",
    shortDescription: "Economic impact analysis of AI transformation",
    perspectiveOn: "AI Economics",
    coverImage:
      "/DCO/The Psychology of Emerging Technology_ How Big Data, AI, and Cognitive ... - Dr Mehmet Yildiz - Google Books/imgi_13_content.jpg",
    rating: 4.7,
    reviewCount: 245,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "AI Economics",
      "Economic Impact",
      "AI Automation",
      "Industry Analysis",
    ],
    isbn: "978-1234567908",
    publishDate: "2025-11-15",
    pageCount: 334,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "AI's economic transformation impact",
    reviewSummary: "Comprehensive analysis of AI's economic implications",
    transformationImpactScore: 9.0,
    actionabilityScore: 4.1,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D2: Digital Cognitive Organization"],
  },

  // Digital Business Platforms (Platforms & Ecosystems)
  {
    id: "designed-for-digital-platforms",
    title:
      "Designed for Digital: How to Architect Your Business for Sustained Success",
    author: "Jeanne W. Ross, Cynthia M. Beath, Martin Mocker",
    description:
      "Building the architectural foundations (Digital Platforms and External Developer Platforms) needed for long-term agility.",
    shortDescription: "Digital platform architecture for business agility",
    perspectiveOn: "Platform Architecture",
    coverImage:
      "/book covers/Designed for Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 312,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Platform Architecture",
      "Digital Platforms",
      "Business Agility",
      "MIT Research",
    ],
    isbn: "978-1234567909",
    publishDate: "2024-08-15",
    pageCount: 278,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Digital platform business architecture",
    reviewSummary: "Definitive guide to platform-based business design",
    transformationImpactScore: 9.2,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D3: Digital Business Platforms"],
  },
  {
    id: "machine-platform-crowd",
    title: "Machine, Platform, Crowd: Harnessing Our Digital Future",
    author: "Andrew McAfee, Erik Brynjolfsson",
    description:
      "Exploring how platform-based models and the 'crowd' disrupt traditional business hierarchies and create new value networks.",
    shortDescription: "Platform economics and crowd-powered business models",
    perspectiveOn: "Platform Economics",
    coverImage: "/DBP/imgi_106_61DnUeDO1aL._SL1057_.jpg",
    rating: 4.8,
    reviewCount: 289,
    category: bookCategories[4], // Innovation
    tags: [
      "Platform Economics",
      "Crowd Sourcing",
      "Digital Disruption",
      "Business Models",
    ],
    isbn: "978-1234567910",
    publishDate: "2025-02-20",
    pageCount: 356,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Platform and crowd-based business transformation",
    reviewSummary: "Insightful analysis of platform-driven business models",
    transformationImpactScore: 8.9,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D3: Digital Business Platforms"],
  },
  {
    id: "digital-infrastructures-innovation",
    title: "Digital Infrastructures for Business Innovation",
    author: "Ray Hackney, et al.",
    description:
      "Understanding the technical and strategic infrastructure required to support modern business ecosystems and platform strategies.",
    shortDescription: "Infrastructure foundations for digital ecosystems",
    perspectiveOn: "Digital Infrastructure",
    coverImage: "/DBP/imgi_25_images.jpg",
    rating: 4.5,
    reviewCount: 198,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Digital Infrastructure",
      "Business Ecosystems",
      "Platform Strategy",
      "Technical Architecture",
    ],
    isbn: "978-1234567911",
    publishDate: "2025-05-10",
    pageCount: 298,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Digital infrastructure for business innovation",
    reviewSummary: "Technical guide to digital business infrastructure",
    transformationImpactScore: 8.4,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D3: Digital Business Platforms"],
  },
  {
    id: "platform-revolution",
    title: "Platform Revolution",
    author:
      "Geoffrey G. Parker, Marshall W. Van Alstyne, Sangeet Paul Choudary",
    description:
      "A fundamental guide on how networked markets are changing the economy and how to build a successful platform business.",
    shortDescription: "Comprehensive guide to platform business models",
    perspectiveOn: "Platform Strategy",
    coverImage: "/DBP/imgi_41_default.jpg",
    rating: 4.7,
    reviewCount: 267,
    category: bookCategories[3], // Strategy
    tags: [
      "Platform Strategy",
      "Network Effects",
      "Digital Markets",
      "Business Models",
    ],
    isbn: "978-1234567912",
    publishDate: "2025-01-25",
    pageCount: 334,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Platform business model development",
    reviewSummary: "Essential guide to building successful platform businesses",
    transformationImpactScore: 9.1,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.7,
    sixDDimensions: ["D3: Digital Business Platforms"],
  },

  // Digital Transformation (Transformation & Change Management)
  {
    id: "technology-fallacy",
    title:
      "The Technology Fallacy: How People Are the Real Key to Digital Transformation",
    author:
      "Gerald C. Kane, Anh Nguyen Phillips, Jonathan R. Copulsky, Garth R. Andrus",
    description:
      "Emphasizing that digital disruption is primarily a people and culture challenge, not just a technology implementation issue.",
    shortDescription: "People-centric approach to digital transformation",
    perspectiveOn: "Human-Centric Transformation",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.8,
    reviewCount: 298,
    category: bookCategories[1], // Leadership
    tags: [
      "People & Culture",
      "Change Management",
      "Digital Leadership",
      "Human-Centric",
    ],
    isbn: "978-1234567913",
    publishDate: "2025-03-30",
    pageCount: 289,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Human-centric digital transformation",
    reviewSummary: "Essential guide to people-focused transformation",
    transformationImpactScore: 9.0,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D4: Digital Transformation"],
  },
  {
    id: "why-digital-transformations-fail",
    title: "Why Digital Transformations Fail",
    author: "Tony Saldanha",
    description:
      "Outlining a five-stage model to move past the 'details' that often derail transformation efforts and ensure successful outcomes.",
    shortDescription: "Five-stage model for transformation success",
    perspectiveOn: "Transformation Management",
    coverImage:
      "/10 book covers/9 Must-Read Digital Transformation Books in 2025 _ Informa TechTarget/imgi_9_Why_Digital_Transformations_Fail_amazon.png",
    rating: 4.6,
    reviewCount: 234,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Transformation Management",
      "Change Strategy",
      "Implementation",
      "Success Factors",
    ],
    isbn: "978-1234567914",
    publishDate: "2025-06-15",
    pageCount: 267,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Avoiding transformation pitfalls",
    reviewSummary: "Practical guide to transformation success",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.8,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D4: Digital Transformation"],
  },
  {
    id: "leading-digital-transformation",
    title: "Leading Digital: Turning Technology into Business Transformation",
    author: "George Westerman, Didier Bonnet, Andrew McAfee",
    description:
      "Research-based insights on how 'Digital Masters' leverage technology for competitive advantage across industries.",
    shortDescription: "Digital Masters' approach to competitive advantage",
    perspectiveOn: "Digital Leadership",
    coverImage:
      "/book covers/Leading Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 356,
    category: bookCategories[1], // Leadership
    tags: [
      "Digital Leadership",
      "Competitive Advantage",
      "Digital Masters",
      "Research-Based",
    ],
    isbn: "978-1234567915",
    publishDate: "2025-04-20",
    pageCount: 312,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Digital leadership for competitive advantage",
    reviewSummary: "Research-backed guide to digital leadership excellence",
    transformationImpactScore: 9.3,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D4: Digital Transformation"],
  },
  {
    id: "digital-to-the-core",
    title:
      "Digital to the Core: Remastering Leadership for Your Industry, Your Enterprise, and Yourself",
    author: "Mark Raskino, Graham Waller",
    description:
      "Reinventing leadership styles to take full advantage of the digital revolution and drive organizational transformation.",
    shortDescription: "Leadership reinvention for digital revolution",
    perspectiveOn: "Digital Leadership Evolution",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.7,
    reviewCount: 189,
    category: bookCategories[1], // Leadership
    tags: [
      "Leadership Evolution",
      "Digital Revolution",
      "Organizational Change",
      "Executive Strategy",
    ],
    isbn: "978-1234567916",
    publishDate: "2025-08-05",
    pageCount: 298,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Leadership transformation for digital age",
    reviewSummary: "Guide to evolving leadership for digital success",
    transformationImpactScore: 8.8,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D4: Digital Transformation"],
  },

  // Digital Workers and Workspace (Future of Work)
  {
    id: "digital-transformation-smes",
    title: "The Digital Transformation of SMEs",
    author: "OECD",
    description:
      "Insights into how smaller enterprises adapt their workforce and workspaces to digital demands and competitive pressures.",
    shortDescription: "SME workforce adaptation to digital demands",
    perspectiveOn: "SME Digital Transformation",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.4,
    reviewCount: 167,
    category: bookCategories[2], // Business Transformation
    tags: [
      "SME Transformation",
      "Workforce Adaptation",
      "Digital Workplace",
      "Small Business",
    ],
    isbn: "978-1234567917",
    publishDate: "2025-09-10",
    pageCount: 245,
    format: ["paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Small business digital workforce transformation",
    reviewSummary: "Practical guide for SME digital transformation",
    transformationImpactScore: 7.9,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.1,
    sixDDimensions: ["D5: Digital Workers and Workspace"],
  },
  {
    id: "digital-hr-workforce",
    title: "Digital HR: A Critical Management Approach",
    author: "Amelia Manuti",
    description:
      "Redefining employee literacy and the labor market in response to digital transformation and changing work dynamics.",
    shortDescription: "HR transformation for digital workforce",
    perspectiveOn: "Digital HR Strategy",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.5,
    reviewCount: 203,
    category: bookCategories[1], // Leadership
    tags: [
      "Digital HR",
      "Employee Development",
      "Labor Market",
      "Workforce Strategy",
    ],
    isbn: "978-1234567918",
    publishDate: "2025-07-20",
    pageCount: 276,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "HR strategy for digital workforce",
    reviewSummary: "Strategic approach to digital HR transformation",
    transformationImpactScore: 8.3,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D5: Digital Workers and Workspace"],
  },
  {
    id: "remote-work-technology",
    title:
      "Remote Work Technology: Tools and Strategies for the Future of Work",
    author: "Future of Work Research Collective",
    description:
      "Bridging the skills gap and education needed for a successful remote-first or hybrid workforce environment.",
    shortDescription: "Technology strategies for remote workforce",
    perspectiveOn: "Remote Work Technology",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.3,
    reviewCount: 145,
    category: bookCategories[4], // Innovation
    tags: [
      "Remote Work",
      "Workforce Technology",
      "Hybrid Work",
      "Digital Tools",
    ],
    isbn: "978-1234567919",
    publishDate: "2025-10-15",
    pageCount: 234,
    format: ["paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Remote work technology implementation",
    reviewSummary: "Practical guide to remote work technology",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.6,
    strategicDepthScore: 3.9,
    sixDDimensions: ["D5: Digital Workers and Workspace"],
  },
  {
    id: "digital-transformation-skills-education",
    title: "Digital Transformation, Skills and Education",
    author: "Various Authors (ResearchGate)",
    description:
      "Analyzing the specific competencies and digital literacy required by the modern digital worker and educational frameworks.",
    shortDescription: "Skills and education for digital workforce",
    perspectiveOn: "Digital Skills Development",
    coverImage: "/book cover/innovation-frameworks.svg",
    rating: 4.2,
    reviewCount: 123,
    category: bookCategories[1], // Leadership
    tags: [
      "Digital Skills",
      "Education",
      "Workforce Development",
      "Digital Literacy",
    ],
    isbn: "978-1234567920",
    publishDate: "2025-11-30",
    pageCount: 198,
    format: ["paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Digital skills and education frameworks",
    reviewSummary: "Comprehensive guide to digital workforce education",
    transformationImpactScore: 8.1,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.2,
    sixDDimensions: ["D5: Digital Workers and Workspace"],
  },

  // Digital Accelerators (Emerging Tech & Innovation)
  {
    id: "digital-operating-model",
    title: "Digital Operating Model: The Future of Business",
    author: "Rajesh Sinha",
    description:
      "Creating digital accelerators and a culture of rapid innovation without excessive capital expenditure or organizational disruption.",
    shortDescription: "Digital operating models for rapid innovation",
    perspectiveOn: "Digital Operations",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.6,
    reviewCount: 178,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Operating Models",
      "Digital Innovation",
      "Rapid Innovation",
      "Business Operations",
    ],
    isbn: "978-1234567921",
    publishDate: "2025-12-10",
    pageCount: 289,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Digital operating model innovation",
    reviewSummary: "Strategic guide to digital operating excellence",
    transformationImpactScore: 8.5,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D6: Digital Accelerators"],
  },
  {
    id: "accelerated-digital-transformation",
    title: "Accelerated Digital Transformation",
    author: "Neetan Chopra",
    description:
      "A step-by-step framework specifically for established organizations to overcome inertia and accelerate digital change.",
    shortDescription: "Framework for accelerating organizational change",
    perspectiveOn: "Acceleration Strategy",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.4,
    reviewCount: 156,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Acceleration",
      "Change Management",
      "Organizational Inertia",
      "Transformation Framework",
    ],
    isbn: "978-1234567922",
    publishDate: "2026-01-15",
    pageCount: 267,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Accelerated transformation frameworks",
    reviewSummary: "Practical framework for transformation acceleration",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D6: Digital Accelerators"],
  },
  {
    id: "digital-transformation-survive-thrive",
    title:
      "Digital Transformation: Survive and Thrive in an Era of Mass Extinction",
    author: "Tom Siebel",
    description:
      "How the convergence of Cloud, Big Data, AI, and IoT acts as a primary accelerator for modern business transformation.",
    shortDescription: "Technology convergence as business accelerator",
    perspectiveOn: "Technology Convergence",
    coverImage:
      "/10 book covers/Digital Transformation_ Survive and Thrive in an Era of Mass Extinction_ Siebel, Thomas M._ 9781948122481_ Amazon.com_ Books/imgi_90_71N3erCu0nL._SL1500_.jpg",
    rating: 4.7,
    reviewCount: 234,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "Technology Convergence",
      "Cloud Computing",
      "Big Data",
      "IoT",
      "AI",
    ],
    isbn: "978-1948122481",
    publishDate: "2025-11-20",
    pageCount: 312,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Technology convergence acceleration",
    reviewSummary: "Strategic guide to technology-driven acceleration",
    transformationImpactScore: 9.1,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.7,
    sixDDimensions: ["D6: Digital Accelerators"],
  },
  {
    id: "driving-digital-leaders-guide",
    title:
      "Driving Digital: The Leader's Guide to Business Transformation Through Technology",
    author: "Isaac Sacolick",
    description:
      "Lessons on piloting emerging technologies and developing innovative digital practices for competitive advantage.",
    shortDescription: "Leadership guide to emerging technology adoption",
    perspectiveOn: "Technology Leadership",
    coverImage:
      "/10 book covers/igital Trailblazer_ Essential Lessons to Jumpstart Transformation and Accelerate Your Technology Leadership Author_ Isaac Sacolick - Google Search/imgi_57_Digital-Trailblazer-Cover.png",
    rating: 4.5,
    reviewCount: 189,
    category: bookCategories[1], // Leadership
    tags: [
      "Technology Leadership",
      "Emerging Tech",
      "Innovation",
      "Digital Practices",
    ],
    isbn: "978-1234567924",
    publishDate: "2025-08-25",
    pageCount: 298,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Emerging technology leadership",
    reviewSummary: "Practical guide to technology-driven innovation",
    transformationImpactScore: 8.6,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D6: Digital Accelerators"],
  },
];

const topBooksThisWeek: Book[] = [
  {
    id: "transform-14-behaviours-top",
    title:
      "Transform! The 14 Behaviours Driving Successful Digital Transformation in the Age of Gen AI",
    author: "Ian Murrin, Rajesh Jethwam, Mike Wright",
    description:
      "Shifts the focus from technology to human behavior, identifying 14 core behaviors essential for successful change in an AI-dominated market.",
    shortDescription: "14 core behaviors for AI-era transformation",
    perspectiveOn: "Human-Centric Leadership",
    coverImage:
      "/10 book covers/Transform! The 14 Behaviours Driving Successful Digital Transformation in the Age of Gen AI - Google Search/imgi_54_71sbLcK+OvL.jpg",
    rating: 4.8,
    reviewCount: 156,
    category: bookCategories[1], // Leadership
    tags: ["Gen AI", "Human Behavior", "Leadership", "Change Management"],
    isbn: "978-1234567901",
    publishDate: "2026-02-15",
    pageCount: 342,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Human-centric digital transformation behaviors",
    reviewSummary:
      "Essential guide for managing human-centric digital shifts in AI era",
    transformationImpactScore: 9.1,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D5: People & Culture", "D3: Digital & AI"],
  },
  {
    id: "co-intelligence-ai",
    title: "Co-Intelligence: Living and Working with AI",
    author: "Ethan Mollick",
    description:
      "Groundbreaking exploration of how humans and AI can work together effectively, offering practical frameworks for AI collaboration in business and daily life.",
    shortDescription: "Human-AI collaboration frameworks",
    perspectiveOn: "AI Collaboration",
    coverImage:
      "/10 book covers/Co-Intelligence_ Living and Working with AI - Google Search/imgi_75_apple-1.jpg",
    rating: 4.7,
    reviewCount: 203,
    category: bookCategories[0], // AI & Machine Learning
    tags: ["AI Collaboration", "Human-AI", "Productivity", "Future of Work"],
    isbn: "978-1234567902",
    publishDate: "2026-01-10",
    pageCount: 298,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Human-AI collaboration and productivity",
    reviewSummary: "Practical guide for effective human-AI collaboration",
    transformationImpactScore: 8.9,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D3: Digital & AI", "D5: People & Culture"],
  },
  {
    id: "digital-transformation-siebel",
    title:
      "Digital Transformation: Survive and Thrive in an Era of Mass Extinction",
    author: "Thomas M. Siebel",
    description:
      "A comprehensive guide to digital transformation from the founder of Siebel Systems, focusing on how organizations can adapt to survive digital disruption.",
    shortDescription: "Survival guide for digital disruption",
    perspectiveOn: "Digital Survival",
    coverImage:
      "/10 book covers/Digital Transformation_ Survive and Thrive in an Era of Mass Extinction_ Siebel, Thomas M._ 9781948122481_ Amazon.com_ Books/imgi_90_71N3erCu0nL._SL1500_.jpg",
    rating: 4.6,
    reviewCount: 189,
    category: bookCategories[2], // Business Transformation
    tags: ["Digital Disruption", "Business Strategy", "Survival", "Innovation"],
    isbn: "978-1948122481",
    publishDate: "2025-11-20",
    pageCount: 267,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Surviving digital disruption and mass extinction",
    reviewSummary: "Strategic guide for thriving in digital disruption era",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D1: Digital Economy", "D4: Operations & Execution"],
  },
  {
    id: "cognitive-organizations-ai",
    title:
      "Cognitive Organizations: Leveraging the Full Power of Generative AI and Intelligent Agents",
    author: "Kenneth Corrêa",
    description:
      "Explores how organizations can transform into cognitive entities that leverage generative AI and intelligent agents for competitive advantage.",
    shortDescription: "Building cognitive organizations with AI",
    perspectiveOn: "Cognitive AI",
    coverImage:
      "/10 book covers/Cognitive Organizations_ Leveraging the Full Power of Generative AI and Intelligent Agents_ Corrêa, Kenneth_ 9788545584650_ Amazon.com_ Books/imgi_61_71dMVhy-LbL._SL1452_.jpg",
    rating: 4.5,
    reviewCount: 167,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "Generative AI",
      "Intelligent Agents",
      "Cognitive Computing",
      "AI Strategy",
    ],
    isbn: "978-8545584650",
    publishDate: "2025-12-05",
    pageCount: 324,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Cognitive organizations and generative AI",
    reviewSummary:
      "Comprehensive guide to building AI-powered cognitive organizations",
    transformationImpactScore: 8.8,
    actionabilityScore: 4.2,
    strategicDepthScore: 4.7,
    sixDDimensions: ["D3: Digital & AI", "D4: Operations & Execution"],
  },
  {
    id: "see-sooner-act-faster",
    title:
      "See Sooner, Act Faster: How Vigilant Leaders Thrive in an Era of Digital Turbulence",
    author: "George Day, Paul Schoemaker",
    description:
      "Management guide for leaders to develop vigilance and agility in rapidly changing digital environments, focusing on early detection and rapid response.",
    shortDescription: "Leadership vigilance in digital turbulence",
    perspectiveOn: "Digital Leadership",
    coverImage:
      "/10 book covers/See Sooner, Act Faster_ How Vigilant Leaders Thrive in an Era of Digital Turbulence (Management on the Cutting Edge) Authors_ George Day and Paul Schoemake - Google Search/imgi_12_images.png",
    rating: 4.4,
    reviewCount: 145,
    category: bookCategories[1], // Leadership
    tags: ["Digital Leadership", "Agility", "Vigilance", "Change Management"],
    isbn: "978-1234567903",
    publishDate: "2025-10-15",
    pageCount: 289,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Leadership vigilance and rapid response",
    reviewSummary:
      "Essential guide for vigilant leadership in digital turbulence",
    transformationImpactScore: 8.3,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.2,
    sixDDimensions: ["D5: People & Culture", "D6: Acceleration"],
  },
  {
    id: "coming-wave-technology",
    title:
      "The Coming Wave: Technology, Power, and the Twenty-First Century's Greatest Dilemma",
    author: "Mustafa Suleyman",
    description:
      "Co-founder of DeepMind explores the unprecedented wave of technological change and its implications for power, society, and human civilization.",
    shortDescription: "Technology's impact on power and society",
    perspectiveOn: "Technology & Society",
    coverImage:
      "/10 book covers/The Coming Wave_ Technology, Power, and the Twenty-First Century's Greatest Dilemma - Google Search/imgi_60_book-foreground.png",
    rating: 4.6,
    reviewCount: 234,
    category: bookCategories[4], // Innovation
    tags: [
      "Technology Trends",
      "AI Ethics",
      "Power Dynamics",
      "Future Society",
    ],
    isbn: "978-1234567904",
    publishDate: "2025-09-20",
    pageCount: 356,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Technology's impact on power and civilization",
    reviewSummary: "Profound exploration of technology's societal implications",
    transformationImpactScore: 9.0,
    actionabilityScore: 3.8,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D3: Digital & AI", "D1: Digital Economy"],
  },
  // Adding 4 more books from the existing featuredBooks to make it 10
  {
    id: "hbr-10-must-reads-digital-top",
    title:
      "HBR's 10 Must Reads on Leading Digital Transformation (Updated and Expanded)",
    author: "Harvard Business Review",
    description:
      "Definitive collection with new insights on Discovery-Driven Digital Transformation and reskilling in the age of AI.",
    shortDescription: "Curated strategic frameworks for executives",
    perspectiveOn: "Strategic Frameworks",
    coverImage:
      "/book covers/Leading Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 289,
    category: bookCategories[3], // Strategy
    tags: ["Strategy", "Executive Leadership", "AI Reskilling", "Frameworks"],
    isbn: "978-1234567905",
    publishDate: "2026-03-01",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "High-level strategic frameworks for digital transformation",
    reviewSummary:
      "Foundational resource for executives seeking strategic guidance",
    transformationImpactScore: 9.3,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D1: Digital Economy", "D4: Operations & Execution"],
  },
  {
    id: "governing-the-machine-top",
    title:
      "Governing the Machine: How to Navigate the Risks of AI and Unlock Its True Potential",
    author: "Ray Eitel-Porter, Dr. Paul Dongha, Miriam Vogel",
    description:
      "Pragmatic framework for AI governance, essential for aligning digital transformation with evolving global regulations like the EU AI Act.",
    shortDescription: "AI governance and regulatory compliance",
    perspectiveOn: "AI Governance",
    coverImage:
      "/book covers/Governing the Machine_ How to navigate the risks of AI and unlock its true ... - Ray Eitel-Porter, Paul Dongha, Miriam Vogel - Google Books/imgi_4_content.jpg",
    rating: 4.7,
    reviewCount: 203,
    category: bookCategories[0], // AI & Machine Learning
    tags: ["AI Governance", "Regulation", "EU AI Act", "Ethics"],
    isbn: "978-1234567906",
    publishDate: "2026-01-20",
    pageCount: 367,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "AI governance and regulatory alignment",
    reviewSummary:
      "Essential guide for navigating AI risks and regulatory compliance",
    transformationImpactScore: 8.9,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D3: Digital & AI", "D2: Platforms"],
  },
  {
    id: "digital-transformation-roadmap-top",
    title:
      "The Digital Transformation Roadmap: Rebuild Your Organization for Continuous Change",
    author: "David L. Rogers",
    description:
      "Follow-up to the classic Playbook, addressing the necessity of building organizations capable of continuous change rather than one-off projects.",
    shortDescription: "Building organizations for continuous change",
    perspectiveOn: "Continuous Transformation",
    coverImage:
      "/book covers/The Digital Transformation Roadmap - Google Books/imgi_3_default.jpg",
    rating: 4.8,
    reviewCount: 234,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Continuous Change",
      "Organizational Design",
      "Planning",
      "Barriers",
    ],
    isbn: "978-1234567907",
    publishDate: "2025-11-15",
    pageCount: 389,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Continuous organizational transformation",
    reviewSummary: "Practical guide for overcoming internal barriers to change",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.8,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D4: Operations & Execution", "D5: People & Culture"],
  },
  {
    id: "designed-for-digital-top",
    title:
      "Designed for Digital: How to Architect Your Business for Sustained Success",
    author: "Jeanne W. Ross, Martin Mocker, Cynthia Beath",
    description:
      "Rigorous research from MIT CISR on re-architecting legacy companies to be as agile as digital natives. The go-to guide for digital architecture.",
    shortDescription: "Architecting businesses for digital agility",
    perspectiveOn: "Digital Architecture",
    coverImage:
      "/book covers/Designed for Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 312,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Digital Architecture",
      "MIT Research",
      "Legacy Transformation",
      "Agility",
    ],
    isbn: "978-1234567908",
    publishDate: "2024-08-15",
    pageCount: 278,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Digital business architecture and agility",
    reviewSummary:
      "Definitive guide for architecting digitally native organizations",
    transformationImpactScore: 9.0,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D2: Platforms", "D6: Acceleration"],
  },
];

const expertReviews = [
  {
    id: "bundle1",
    title: "Digital Economy Transformation",
    description:
      "Books focused on Digital Economy and business model innovation",
    books: [
      frontierBooks.find(
        (book) => book.id === "digital-transformation-playbook",
      ),
      frontierBooks.find((book) => book.id === "economics-of-data-analytics"),
      frontierBooks.find((book) => book.id === "driving-digital-strategy"),
      frontierBooks.find(
        (book) => book.id === "demand-driven-business-strategy",
      ),
    ].filter(Boolean) as Book[],
    dimensions: ["D1: Digital Economy"],
    curatedBy: "Business Strategy Experts",
    targetAudience: "CEOs and Business Leaders",
  },
  {
    id: "bundle2",
    title: "Digital Cognitive Organizations",
    description:
      "Books focused on AI, cognitive systems, and intelligent organizations",
    books: [
      frontierBooks.find(
        (book) => book.id === "digital-transformation-subconscious-minds",
      ),
      frontierBooks.find((book) => book.id === "integrating-business-ai"),
      frontierBooks.find(
        (book) => book.id === "digital-hr-critical-management",
      ),
      frontierBooks.find((book) => book.id === "sizing-prize-ai-future"),
    ].filter(Boolean) as Book[],
    dimensions: ["D2: Digital Cognitive Organization"],
    curatedBy: "AI Strategy Leaders",
    targetAudience: "CTOs and AI Directors",
  },
  {
    id: "bundle3",
    title: "Digital Business Platforms",
    description: "Books on platforms, ecosystems, and digital architecture",
    books: [
      frontierBooks.find(
        (book) => book.id === "designed-for-digital-platforms",
      ),
      frontierBooks.find((book) => book.id === "machine-platform-crowd"),
      frontierBooks.find(
        (book) => book.id === "digital-infrastructures-innovation",
      ),
      frontierBooks.find((book) => book.id === "platform-revolution"),
    ].filter(Boolean) as Book[],
    dimensions: ["D3: Digital Business Platforms"],
    curatedBy: "Platform Architecture Experts",
    targetAudience: "Solution Architects and Platform Leaders",
  },
  {
    id: "bundle4",
    title: "Digital Transformation Strategy",
    description: "Books on transformation strategies and change management",
    books: [
      frontierBooks.find((book) => book.id === "technology-fallacy"),
      frontierBooks.find(
        (book) => book.id === "why-digital-transformations-fail",
      ),
      frontierBooks.find(
        (book) => book.id === "leading-digital-transformation",
      ),
      frontierBooks.find((book) => book.id === "digital-to-the-core"),
    ].filter(Boolean) as Book[],
    dimensions: ["D4: Digital Transformation"],
    curatedBy: "Transformation Consultants",
    targetAudience: "Change Management Leaders",
  },
  {
    id: "bundle5",
    title: "Digital Workers and Workspace",
    description: "Books on future of work, remote work, and digital workforce",
    books: [
      frontierBooks.find((book) => book.id === "digital-transformation-smes"),
      frontierBooks.find((book) => book.id === "digital-hr-workforce"),
      frontierBooks.find((book) => book.id === "remote-work-technology"),
      frontierBooks.find(
        (book) => book.id === "digital-transformation-skills-education",
      ),
    ].filter(Boolean) as Book[],
    dimensions: ["D5: Digital Workers and Workspace"],
    curatedBy: "Future of Work Experts",
    targetAudience: "HR Leaders and Workforce Strategists",
  },
  {
    id: "bundle6",
    title: "Digital Accelerators",
    description: "Books on emerging tech, innovation, and accelerators",
    books: [
      frontierBooks.find((book) => book.id === "digital-operating-model"),
      frontierBooks.find(
        (book) => book.id === "accelerated-digital-transformation",
      ),
      frontierBooks.find(
        (book) => book.id === "digital-transformation-survive-thrive",
      ),
      frontierBooks.find((book) => book.id === "driving-digital-leaders-guide"),
    ].filter(Boolean) as Book[],
    dimensions: ["D6: Digital Accelerators"],
    curatedBy: "Innovation Leaders",
    targetAudience: "Innovation Directors and Tech Scouts",
  },
];

export const authorInfo: Author = {
  id: "1",
  name: "Dr. Stéphane Niango",
  bio: "With over 15 years of experience in digital transformation consulting, Dr. Stéphane Niango has helped Fortune 500 companies navigate complex technological changes and achieve sustainable growth. A recognized thought leader in the industry, he has spoken at major conferences worldwide and contributed to numerous publications on digital innovation.",
  avatar: "/images/SN.svg",
  credentials: [
    "15+ years in digital transformation",
    "Consulted for 100+ Fortune 500 companies",
    "International keynote speaker",
    "Published researcher in digital innovation",
  ],
  bookCount: 6,
  followerCount: 25000,
  socialLinks: {
    linkedin: "https://linkedin.com/in/stephane-niango",
    twitter: "https://twitter.com/stephane_niango",
    website: "https://digitalqatalyst.com",
  },
};

export const testimonials: Testimonial[] = [
  {
    id: "1",
    content:
      "This book transformed how we approach digital initiatives. The practical frameworks are invaluable for any leader.",
    author: "Sarah Johnson",
    title: "CTO",
    company: "Tech Innovations Inc.",
    rating: 5,
    avatar: "/images/testimonials/sarah-johnson.jpg",
  },
  {
    id: "2",
    content:
      "Clear, actionable insights backed by real-world experience. A must-read for digital transformation professionals.",
    author: "Michael Chen",
    title: "VP Digital Strategy",
    company: "Global Corp",
    rating: 5,
    avatar: "/images/testimonials/michael-chen.jpg",
  },
  {
    id: "3",
    content:
      "Excellent resource for understanding the complexities of modern digital transformation challenges.",
    author: "Emily Rodriguez",
    title: "Director of Innovation",
    company: "StartupXYZ",
    rating: 4,
    avatar: "/images/testimonials/emily-rodriguez.jpg",
  },
];

export const expertInterviews: Interview[] = [
  {
    id: "1",
    title: "The Future of AI in Business Strategy",
    expert: {
      name: "Dr. Sarah Mitchell",
      title: "AI Research Director",
      avatar: "/images/experts/sarah-mitchell.jpg",
    },
    thumbnail: "/images/interviews/ai-business-strategy.jpg",
    snippet:
      "Exploring how artificial intelligence is reshaping strategic decision-making processes across industries.",
    readTime: 8,
    publishDate: "2024-02-15",
    url: "/interviews/ai-business-strategy",
  },
  {
    id: "2",
    title: "Leading Through Digital Disruption",
    expert: {
      name: "James Thompson",
      title: "Former CEO, TechCorp",
      avatar: "/images/experts/james-thompson.jpg",
    },
    thumbnail: "/images/interviews/digital-disruption.jpg",
    snippet:
      "Insights from a seasoned executive on navigating organizational change in the digital age.",
    readTime: 12,
    publishDate: "2024-01-28",
    url: "/interviews/digital-disruption-leadership",
  },
  {
    id: "3",
    title: "Building Data-Driven Organizations",
    expert: {
      name: "Dr. Maria Santos",
      title: "Chief Data Officer",
      avatar: "/images/experts/maria-santos.jpg",
    },
    thumbnail: "/images/interviews/data-driven-orgs.jpg",
    snippet:
      "Practical strategies for embedding data analytics into organizational decision-making processes.",
    readTime: 10,
    publishDate: "2024-02-05",
    url: "/interviews/data-driven-organizations",
  },
];

// Subscription plans removed - using content access tiers instead

// Briefly Noted Books for Sidebar
const brieflyNotedBooks: BrieflyNotedBook[] = [
  {
    id: "bn1",
    title: "Logistics and Digital Transformation",
    author: "Supply Chain Institute",
    briefReview:
      "A practical guide for modern supply chains, this book focuses on how digital transformation is reshaping the logistics industry. While it's packed with case studies, it falls short in providing actionable advice for small-to-medium enterprises.",
  },
  {
    id: "bn2",
    title: "AI Ethics in Practice",
    author: "Ethics Research Group",
    briefReview:
      "An essential read for understanding the ethical implications of AI deployment. The book provides frameworks for responsible AI implementation but lacks depth in addressing regulatory compliance challenges.",
  },
  {
    id: "bn3",
    title: "Cybersecurity for Digital Leaders",
    author: "Security Experts Collective",
    briefReview:
      "Comprehensive coverage of cybersecurity challenges in digital transformation. Strong on threat analysis but could benefit from more practical implementation guidance for non-technical executives.",
  },
];

// Framework Rankings for Monthly Feature
const frameworkRankings: FrameworkRanking[] = [
  {
    id: "fr1",
    name: "The Reshuffle Model",
    author: "Sangeet Paul Choudary",
    description:
      "A strategic framework for aligning organizational culture and leadership with evolving digital technologies. Focuses on platform thinking and ecosystem orchestration.",
    adoptionRate: 78,
    slug: "reshuffle-model",
  },
  {
    id: "fr2",
    name: "The Digital Master Framework",
    author: "George Westerman",
    description:
      "Focused on creating a digital culture across all levels of an organization. Emphasizes the importance of digital leadership and governance structures.",
    adoptionRate: 65,
    slug: "digital-master-framework",
  },
  {
    id: "fr3",
    name: "AI-First Transformation Model",
    author: "MIT Digital Strategy Lab",
    description:
      "A comprehensive approach to building AI capabilities into organizational DNA. Addresses both technical implementation and cultural change management.",
    adoptionRate: 52,
    slug: "ai-first-transformation",
  },
];

// Export all data
export {
  featuredBooks,
  frontierBooks,
  topBooksThisWeek,
  expertReviews,
  brieflyNotedBooks,
  frameworkRankings,
};
