import {
  Book,
  BookCategory,
  Author,
  Testimonial,
  Interview,
  BrieflyNotedBook,
  FrameworkRanking,
} from "../types/book";

export const bookCategories: BookCategory[] = [
  {
    id: "1",
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    description:
      "Cutting-edge insights on artificial intelligence and ML applications",
    icon: "🤖",
    color: "bg-blue-500",
  },
  {
    id: "2",
    name: "Leadership",
    slug: "leadership",
    description: "Strategic leadership in the digital transformation era",
    icon: "👥",
    color: "bg-purple-500",
  },
  {
    id: "3",
    name: "Business Transformation",
    slug: "business-transformation",
    description: "Comprehensive guides to organizational change",
    icon: "🔄",
    color: "bg-green-500",
  },
  {
    id: "4",
    name: "Strategy",
    slug: "strategy",
    description: "Digital strategy frameworks and methodologies",
    icon: "🎯",
    color: "bg-orange-500",
  },
  {
    id: "5",
    name: "Innovation",
    slug: "innovation",
    description: "Driving innovation in digital-first organizations",
    icon: "💡",
    color: "bg-yellow-500",
  },
  {
    id: "6",
    name: "Data & Analytics",
    slug: "data-analytics",
    description: "Leveraging data for competitive advantage",
    icon: "📊",
    color: "bg-teal-500",
  },
];

// Featured Books for 2025-2026 Digital Transformation Reviews
const featuredBooks: Book[] = [
  {
    id: "6xd-six-digital-perspectives",
    title: "6xD: The Six Digital Perspectives",
    author: "Dr. Stephane Niango",
    description:
      "A provocative and ambitious blueprint for the evolution of traditional businesses into Digital Cognitive Organizations (DCOs). Challenges conventional wisdom about digital transformation barriers.",
    shortDescription: "Blueprint for Digital Cognitive Organizations",
    perspectiveOn: "Cognitive Architecture",
    coverImage: "/book covers/6xd-removepg-preview.png",
    rating: 4.8,
    reviewCount: 287,
    category: bookCategories[2],
    tags: [
      "Digital Transformation",
      "AI",
      "Cognitive Architecture",
      "6xD Framework",
    ],
    isbn: "978-1234567890",
    publishDate: "2025-01-15",
    pageCount: 385,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Digital Cognitive Organizations and 6xD Framework",
    reviewSummary:
      "Ambitious blueprint for transforming businesses into Digital Cognitive Organizations",
    transformationImpactScore: 9.2,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.9,
    sixDDimensions: [
      "D1: Digital Economy",
      "D2: Platforms",
      "D3: Digital & AI",
      "D4: Operations & Execution",
      "D5: People & Culture",
      "D6: Acceleration",
    ],
  },
  {
    id: "2",
    title: "AI Leadership in the Digital Age",
    author: "A. Pauceanu",
    description:
      "With a focus on aligning business strategy with AI capabilities, this book provides a bridge between technical knowledge and practical business applications.",
    shortDescription: "Bridging tech knowledge with business use",
    perspectiveOn: "AI Strategy",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.7,
    reviewCount: 289,
    category: bookCategories[0],
    tags: ["AI", "Business Strategy", "Integration", "2026"],
    isbn: "978-1234567891",
    publishDate: "2026-02-01",
    pageCount: 312,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Bridging tech knowledge with business use",
    reviewSummary:
      "Essential guide for aligning business strategy with AI capabilities",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D3: Digital & AI", "D2: Platforms"],
  },
  {
    id: "3",
    title: "Strategic Digital Leadership",
    author: "E. Iveroth",
    description:
      "Iveroth's book is a critical resource for leaders, offering a comprehensive guide on managing governance, control, and execution at scale during digital transformation.",
    shortDescription: "Governance and control in organizations",
    perspectiveOn: "Execution",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.8,
    reviewCount: 256,
    category: bookCategories[1],
    tags: ["Leadership", "Governance", "Execution", "Scale"],
    isbn: "978-1234567892",
    publishDate: "2025-03-20",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Governance and control in organizations",
    reviewSummary:
      "Comprehensive guide for managing governance and execution at scale",
    transformationImpactScore: 8.2,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.4,
    sixDDimensions: ["D5: People & Culture", "D4: Operations & Execution"],
  },
  {
    id: "4",
    title: "Data-Driven Decision Making",
    author: "Ray Kurzweil",
    description:
      "A fascinating exploration of the future of AI and its convergence with humanity, offering a bold vision for the future of digital transformation.",
    shortDescription: "Predictions on human-AI merging",
    perspectiveOn: "Future Vision",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.6,
    reviewCount: 423,
    category: bookCategories[0],
    tags: ["AI", "Future", "Singularity", "Innovation"],
    isbn: "978-1234567893",
    publishDate: "2025-06-10",
    pageCount: 456,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Predictions on human-AI merging",
    reviewSummary: "Bold vision for the future of AI and humanity convergence",
    transformationImpactScore: 7.2,
    actionabilityScore: 3.8,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D3: Digital & AI", "D6: Acceleration"],
  },
  {
    id: "5",
    title: "Innovation Frameworks for Digital Transformation",
    author: "Ethan Mollick",
    description:
      "This groundbreaking book addresses the ethical challenges and opportunities of human-AI collaboration, offering frameworks to navigate the evolving dynamics of AI ethics in business.",
    shortDescription: "Human-AI collaboration and dynamics",
    perspectiveOn: "AI Ethics",
    coverImage: "/book cover/innovation-frameworks.svg",
    rating: 4.8,
    reviewCount: 198,
    category: bookCategories[0],
    tags: ["AI Ethics", "Collaboration", "Human-AI", "Frameworks"],
    isbn: "978-1234567894",
    publishDate: "2025-04-15",
    pageCount: 324,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Human-AI collaboration and dynamics",
    reviewSummary:
      "Groundbreaking exploration of ethical human-AI collaboration",
    transformationImpactScore: 8.0,
    actionabilityScore: 4.3,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D3: Digital & AI", "D5: People & Culture"],
  },
  {
    id: "6",
    title: "The Future of Work in Digital Economy",
    author: "Karen Hao",
    description:
      "An in-depth exploration of OpenAI's journey and its impact on the broader tech ecosystem, this book is a must-read for anyone interested in the innovation behind AI transformation.",
    shortDescription: "Inside story of OpenAI and Sam Altman",
    perspectiveOn: "Innovation",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.7,
    reviewCount: 267,
    category: bookCategories[4],
    tags: ["OpenAI", "Innovation", "Tech Ecosystem", "AI History"],
    isbn: "978-1234567895",
    publishDate: "2025-05-20",
    pageCount: 378,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Inside story of OpenAI and Sam Altman",
    reviewSummary: "In-depth exploration of OpenAI's transformative journey",
    transformationImpactScore: 7.5,
    actionabilityScore: 3.9,
    strategicDepthScore: 4.2,
    sixDDimensions: ["D3: Digital & AI", "D1: Digital Economy"],
  },
  {
    id: "7",
    title: "How AI Ate the World",
    author: "Chris Stokel-Walker",
    description:
      "Stokel-Walker's book provides a unique perspective on AI's transformation of industries. It covers case studies of how AI is reshaping traditional business operations.",
    shortDescription: "AI's impact on industry operations",
    perspectiveOn: "Industry Shifts",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.5,
    reviewCount: 189,
    category: bookCategories[2],
    tags: [
      "Industry Transformation",
      "Case Studies",
      "AI Impact",
      "Operations",
    ],
    isbn: "978-1234567896",
    publishDate: "2025-07-12",
    pageCount: 342,
    format: ["paperback", "ebook"],
    availability: "available",
    keyFocusArea: "AI's impact on industry operations",
    reviewSummary: "Unique perspective on AI's transformation of industries",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.1,
    strategicDepthScore: 4.0,
    sixDDimensions: ["D3: Digital & AI", "D4: Operations & Execution"],
  },
  {
    id: "8",
    title: "Digital Resilience & Cybersecurity",
    author: "T. Singh",
    description:
      "This book tackles the importance of digital resilience in supply chains, offering strategies for organizations to safeguard against cybersecurity threats during digital transformation.",
    shortDescription: "Cybersecurity in supply chains",
    perspectiveOn: "Resilience",
    coverImage: "/book cover/strategic-digital-leadership.svg",
    rating: 4.6,
    reviewCount: 234,
    category: bookCategories[3],
    tags: ["Cybersecurity", "Resilience", "Supply Chain", "Risk Management"],
    isbn: "978-1234567897",
    publishDate: "2025-08-30",
    pageCount: 289,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Cybersecurity in supply chains",
    reviewSummary:
      "Essential strategies for digital resilience and cybersecurity",
    transformationImpactScore: 8.1,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.1,
    sixDDimensions: ["D2: Platforms", "D4: Operations & Execution"],
  },
  {
    id: "9",
    title: "Quantum Computing for Business Leaders",
    author: "M. Chen",
    description:
      "A comprehensive guide to understanding quantum computing's potential impact on business strategy and digital transformation initiatives.",
    shortDescription: "Quantum computing's business applications",
    perspectiveOn: "Emerging Tech",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.3,
    reviewCount: 156,
    category: bookCategories[0],
    tags: ["Quantum Computing", "Emerging Tech", "Business Strategy"],
    isbn: "978-1234567898",
    publishDate: "2025-09-15",
    pageCount: 267,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Quantum computing's business applications",
    reviewSummary: "Strategic guide to quantum computing for business leaders",
    transformationImpactScore: 6.8,
    actionabilityScore: 3.5,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D3: Digital & AI", "D6: Acceleration"],
  },
  {
    id: "10",
    title: "Spatial Commerce Revolution",
    author: "L. Rodriguez",
    description:
      "Exploring the intersection of AR/VR, spatial computing, and commerce to create immersive customer experiences.",
    shortDescription: "AR/VR in commerce and customer experience",
    perspectiveOn: "Spatial Tech",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.4,
    reviewCount: 203,
    category: bookCategories[4],
    tags: ["AR/VR", "Spatial Computing", "Commerce", "Customer Experience"],
    isbn: "978-1234567899",
    publishDate: "2025-10-20",
    pageCount: 298,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "AR/VR in commerce and customer experience",
    reviewSummary: "Revolutionary approach to spatial commerce experiences",
    transformationImpactScore: 7.1,
    actionabilityScore: 4.0,
    strategicDepthScore: 3.9,
    sixDDimensions: ["D1: Digital Economy", "D3: Digital & AI"],
  },
];

// Mock data for different sections
const frontierBooks: Book[] = [
  {
    id: "transform-14-behaviours",
    title:
      "Transform! The 14 Behaviours Driving Successful Digital Transformation in the Age of Gen AI",
    author: "Ian Murrin, Rajesh Jethwam, Mike Wright",
    description:
      "Shifts the focus from technology to human behavior, identifying 14 core behaviors essential for successful change in an AI-dominated market.",
    shortDescription: "14 core behaviors for AI-era transformation",
    perspectiveOn: "Human-Centric Leadership",
    coverImage: "/book covers/download (1).png",
    rating: 4.8,
    reviewCount: 156,
    category: bookCategories[1], // Leadership
    tags: ["Gen AI", "Human Behavior", "Leadership", "Change Management"],
    isbn: "978-1234567901",
    publishDate: "2026-02-15",
    pageCount: 342,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Human-centric digital transformation behaviors",
    reviewSummary:
      "Essential guide for managing human-centric digital shifts in AI era",
    transformationImpactScore: 9.1,
    actionabilityScore: 4.7,
    strategicDepthScore: 4.5,
    sixDDimensions: ["D5: People & Culture", "D3: Digital & AI"],
  },
  {
    id: "hbr-10-must-reads-digital",
    title:
      "HBR's 10 Must Reads on Leading Digital Transformation (Updated and Expanded)",
    author: "Harvard Business Review",
    description:
      "Definitive collection with new insights on Discovery-Driven Digital Transformation and reskilling in the age of AI.",
    shortDescription: "Curated strategic frameworks for executives",
    perspectiveOn: "Strategic Frameworks",
    coverImage:
      "/book covers/Leading Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 289,
    category: bookCategories[3], // Strategy
    tags: ["Strategy", "Executive Leadership", "AI Reskilling", "Frameworks"],
    isbn: "978-1234567902",
    publishDate: "2026-03-01",
    pageCount: 298,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "High-level strategic frameworks for digital transformation",
    reviewSummary:
      "Foundational resource for executives seeking strategic guidance",
    transformationImpactScore: 9.3,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.9,
    sixDDimensions: ["D1: Digital Economy", "D4: Operations & Execution"],
  },
  {
    id: "governing-the-machine",
    title:
      "Governing the Machine: How to Navigate the Risks of AI and Unlock Its True Potential",
    author: "Ray Eitel-Porter, Dr. Paul Dongha, Miriam Vogel",
    description:
      "Pragmatic framework for AI governance, essential for aligning digital transformation with evolving global regulations like the EU AI Act.",
    shortDescription: "AI governance and regulatory compliance",
    perspectiveOn: "AI Governance",
    coverImage:
      "/book covers/Governing the Machine_ How to navigate the risks of AI and unlock its true ... - Ray Eitel-Porter, Paul Dongha, Miriam Vogel - Google Books/imgi_4_content.jpg",
    rating: 4.7,
    reviewCount: 203,
    category: bookCategories[0], // AI & Machine Learning
    tags: ["AI Governance", "Regulation", "EU AI Act", "Ethics"],
    isbn: "978-1234567903",
    publishDate: "2026-01-20",
    pageCount: 367,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "AI governance and regulatory alignment",
    reviewSummary:
      "Essential guide for navigating AI risks and regulatory compliance",
    transformationImpactScore: 8.9,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D3: Digital & AI", "D2: Platforms"],
  },
  {
    id: "digital-transformation-roadmap-rogers",
    title:
      "The Digital Transformation Roadmap: Rebuild Your Organization for Continuous Change",
    author: "David L. Rogers",
    description:
      "Follow-up to the classic Playbook, addressing the necessity of building organizations capable of continuous change rather than one-off projects.",
    shortDescription: "Building organizations for continuous change",
    perspectiveOn: "Continuous Transformation",
    coverImage:
      "/book covers/The Digital Transformation Roadmap - Google Books/imgi_3_default.jpg",
    rating: 4.8,
    reviewCount: 234,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Continuous Change",
      "Organizational Design",
      "Planning",
      "Barriers",
    ],
    isbn: "978-1234567904",
    publishDate: "2025-11-15",
    pageCount: 389,
    format: ["hardcover", "paperback", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Continuous organizational transformation",
    reviewSummary: "Practical guide for overcoming internal barriers to change",
    transformationImpactScore: 8.7,
    actionabilityScore: 4.8,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D4: Operations & Execution", "D5: People & Culture"],
  },
  {
    id: "digital-resilience-cybersecurity",
    title: "Digital Resilience, Cybersecurity and Supply Chains",
    author: "Tarnveer Singh",
    description:
      "Explores the critical intersection of digital transformation and security, offering strategies for maintaining resilience against modern vulnerabilities.",
    shortDescription: "Security and resilience in digital transformation",
    perspectiveOn: "Digital Security",
    coverImage:
      "/book covers/Digital Resilience, Cybersecurity and Supply Chains - Google Books/imgi_3_default.jpg",
    rating: 4.6,
    reviewCount: 178,
    category: bookCategories[3], // Strategy
    tags: ["Cybersecurity", "Supply Chain", "Resilience", "Risk Management"],
    isbn: "978-1234567905",
    publishDate: "2025-09-30",
    pageCount: 312,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Digital resilience and cybersecurity strategies",
    reviewSummary:
      "Critical guide for securing digital transformation initiatives",
    transformationImpactScore: 8.4,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.3,
    sixDDimensions: ["D2: Platforms", "D4: Operations & Execution"],
  },
  {
    id: "designed-for-digital",
    title:
      "Designed for Digital: How to Architect Your Business for Sustained Success",
    author: "Jeanne W. Ross, Martin Mocker, Cynthia Beath",
    description:
      "Rigorous research from MIT CISR on re-architecting legacy companies to be as agile as digital natives. The go-to guide for digital architecture.",
    shortDescription: "Architecting businesses for digital agility",
    perspectiveOn: "Digital Architecture",
    coverImage:
      "/book covers/Designed for Digital - Google Books/imgi_3_default.jpg",
    rating: 4.9,
    reviewCount: 312,
    category: bookCategories[2], // Business Transformation
    tags: [
      "Digital Architecture",
      "MIT Research",
      "Legacy Transformation",
      "Agility",
    ],
    isbn: "978-1234567906",
    publishDate: "2024-08-15",
    pageCount: 278,
    format: ["hardcover", "paperback", "ebook"],
    availability: "available",
    keyFocusArea: "Digital business architecture and agility",
    reviewSummary:
      "Definitive guide for architecting digitally native organizations",
    transformationImpactScore: 9.0,
    actionabilityScore: 4.6,
    strategicDepthScore: 4.8,
    sixDDimensions: ["D2: Platforms", "D6: Acceleration"],
  },
  {
    id: "quantum-business-advantage",
    title: "Quantum Computing for Business Advantage",
    author: "Dr. Sarah Chen, Michael Torres",
    description:
      "Comprehensive guide to understanding quantum computing's potential impact on business strategy and competitive advantage in the digital economy.",
    shortDescription: "Quantum computing's business applications",
    perspectiveOn: "Quantum Technology",
    coverImage: "/book cover/data-driven-decision-making.svg",
    rating: 4.5,
    reviewCount: 134,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "Quantum Computing",
      "Emerging Tech",
      "Business Strategy",
      "Competitive Advantage",
    ],
    isbn: "978-1234567907",
    publishDate: "2026-01-10",
    pageCount: 289,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Quantum computing business applications",
    reviewSummary: "Strategic guide to quantum computing for business leaders",
    transformationImpactScore: 7.8,
    actionabilityScore: 4.2,
    strategicDepthScore: 4.6,
    sixDDimensions: ["D3: Digital & AI", "D6: Acceleration"],
  },
  {
    id: "spatial-commerce-revolution",
    title: "The Spatial Commerce Revolution: AR, VR, and the Future of Retail",
    author: "Lisa Rodriguez, James Park",
    description:
      "Exploring the intersection of AR/VR, spatial computing, and commerce to create immersive customer experiences and transform retail landscapes.",
    shortDescription: "AR/VR transforming retail and commerce",
    perspectiveOn: "Spatial Technology",
    coverImage: "/book cover/future-of-work.svg",
    rating: 4.6,
    reviewCount: 167,
    category: bookCategories[4], // Innovation
    tags: [
      "Spatial Commerce",
      "AR/VR",
      "Retail Transformation",
      "Customer Experience",
    ],
    isbn: "978-1234567908",
    publishDate: "2025-12-05",
    pageCount: 324,
    format: ["hardcover", "ebook", "audiobook"],
    availability: "available",
    keyFocusArea: "Spatial commerce and immersive retail",
    reviewSummary: "Revolutionary approach to spatial commerce experiences",
    transformationImpactScore: 8.2,
    actionabilityScore: 4.4,
    strategicDepthScore: 4.1,
    sixDDimensions: ["D1: Digital Economy", "D3: Digital & AI"],
  },
  {
    id: "agentic-ai-enterprise",
    title: "Agentic AI in the Enterprise: Building Autonomous Business Systems",
    author: "Dr. Alex Kumar, Rachel Thompson",
    description:
      "Comprehensive guide to implementing agentic AI systems that can operate autonomously, make decisions, and drive business outcomes without constant human intervention.",
    shortDescription: "Building autonomous AI business systems",
    perspectiveOn: "Agentic AI",
    coverImage: "/book cover/ai-leadership-digital-age.svg",
    rating: 4.7,
    reviewCount: 198,
    category: bookCategories[0], // AI & Machine Learning
    tags: [
      "Agentic AI",
      "Autonomous Systems",
      "Enterprise AI",
      "Business Automation",
    ],
    isbn: "978-1234567909",
    publishDate: "2026-02-28",
    pageCount: 356,
    format: ["hardcover", "ebook"],
    availability: "available",
    keyFocusArea: "Autonomous AI systems for enterprise",
    reviewSummary: "Essential guide for implementing agentic AI in business",
    transformationImpactScore: 9.2,
    actionabilityScore: 4.5,
    strategicDepthScore: 4.7,
    sixDDimensions: ["D3: Digital & AI", "D4: Operations & Execution"],
  },
];
const topBooksThisWeek = featuredBooks.slice(0, 10);
const expertReviews = [
  {
    id: "bundle1",
    title: "The CEO's First 100 Days",
    description: "Books focused on Digital Economy and People & Culture",
    books: featuredBooks.slice(0, 3),
    dimensions: ["D1: Digital Economy", "D5: People & Culture"],
    curatedBy: "C-Suite Experts",
    targetAudience: "Senior Leadership",
  },
  {
    id: "bundle2",
    title: "The AI Transformation Toolkit",
    description: "Books focused on Platforms and AI",
    books: featuredBooks.slice(1, 4),
    dimensions: ["D2: Platforms", "D3: Digital & AI"],
    curatedBy: "Technology Leaders",
    targetAudience: "CTOs and Tech Directors",
  },
  {
    id: "bundle3",
    title: "Operational Excellence",
    description: "Books on Execution for practitioners and managers",
    books: featuredBooks.slice(2, 5),
    dimensions: ["D4: Operations & Execution", "D5: People & Culture"],
    curatedBy: "Operations Experts",
    targetAudience: "Project Managers and Operations Leaders",
  },
];

export const authorInfo: Author = {
  id: "1",
  name: "Dr. Stéphane Niango",
  bio: "With over 15 years of experience in digital transformation consulting, Dr. Stéphane Niango has helped Fortune 500 companies navigate complex technological changes and achieve sustainable growth. A recognized thought leader in the industry, he has spoken at major conferences worldwide and contributed to numerous publications on digital innovation.",
  avatar: "/images/SN.svg",
  credentials: [
    "15+ years in digital transformation",
    "Consulted for 100+ Fortune 500 companies",
    "International keynote speaker",
    "Published researcher in digital innovation",
  ],
  bookCount: 6,
  followerCount: 25000,
  socialLinks: {
    linkedin: "https://linkedin.com/in/stephane-niango",
    twitter: "https://twitter.com/stephane_niango",
    website: "https://digitalqatalyst.com",
  },
};

export const testimonials: Testimonial[] = [
  {
    id: "1",
    content:
      "This book transformed how we approach digital initiatives. The practical frameworks are invaluable for any leader.",
    author: "Sarah Johnson",
    title: "CTO",
    company: "Tech Innovations Inc.",
    rating: 5,
    avatar: "/images/testimonials/sarah-johnson.jpg",
  },
  {
    id: "2",
    content:
      "Clear, actionable insights backed by real-world experience. A must-read for digital transformation professionals.",
    author: "Michael Chen",
    title: "VP Digital Strategy",
    company: "Global Corp",
    rating: 5,
    avatar: "/images/testimonials/michael-chen.jpg",
  },
  {
    id: "3",
    content:
      "Excellent resource for understanding the complexities of modern digital transformation challenges.",
    author: "Emily Rodriguez",
    title: "Director of Innovation",
    company: "StartupXYZ",
    rating: 4,
    avatar: "/images/testimonials/emily-rodriguez.jpg",
  },
];

export const expertInterviews: Interview[] = [
  {
    id: "1",
    title: "The Future of AI in Business Strategy",
    expert: {
      name: "Dr. Sarah Mitchell",
      title: "AI Research Director",
      avatar: "/images/experts/sarah-mitchell.jpg",
    },
    thumbnail: "/images/interviews/ai-business-strategy.jpg",
    snippet:
      "Exploring how artificial intelligence is reshaping strategic decision-making processes across industries.",
    readTime: 8,
    publishDate: "2024-02-15",
    url: "/interviews/ai-business-strategy",
  },
  {
    id: "2",
    title: "Leading Through Digital Disruption",
    expert: {
      name: "James Thompson",
      title: "Former CEO, TechCorp",
      avatar: "/images/experts/james-thompson.jpg",
    },
    thumbnail: "/images/interviews/digital-disruption.jpg",
    snippet:
      "Insights from a seasoned executive on navigating organizational change in the digital age.",
    readTime: 12,
    publishDate: "2024-01-28",
    url: "/interviews/digital-disruption-leadership",
  },
  {
    id: "3",
    title: "Building Data-Driven Organizations",
    expert: {
      name: "Dr. Maria Santos",
      title: "Chief Data Officer",
      avatar: "/images/experts/maria-santos.jpg",
    },
    thumbnail: "/images/interviews/data-driven-orgs.jpg",
    snippet:
      "Practical strategies for embedding data analytics into organizational decision-making processes.",
    readTime: 10,
    publishDate: "2024-02-05",
    url: "/interviews/data-driven-organizations",
  },
];

// Subscription plans removed - using content access tiers instead

// Briefly Noted Books for Sidebar
const brieflyNotedBooks: BrieflyNotedBook[] = [
  {
    id: "bn1",
    title: "Logistics and Digital Transformation",
    author: "Supply Chain Institute",
    briefReview:
      "A practical guide for modern supply chains, this book focuses on how digital transformation is reshaping the logistics industry. While it's packed with case studies, it falls short in providing actionable advice for small-to-medium enterprises.",
  },
  {
    id: "bn2",
    title: "AI Ethics in Practice",
    author: "Ethics Research Group",
    briefReview:
      "An essential read for understanding the ethical implications of AI deployment. The book provides frameworks for responsible AI implementation but lacks depth in addressing regulatory compliance challenges.",
  },
  {
    id: "bn3",
    title: "Cybersecurity for Digital Leaders",
    author: "Security Experts Collective",
    briefReview:
      "Comprehensive coverage of cybersecurity challenges in digital transformation. Strong on threat analysis but could benefit from more practical implementation guidance for non-technical executives.",
  },
];

// Framework Rankings for Monthly Feature
const frameworkRankings: FrameworkRanking[] = [
  {
    id: "fr1",
    name: "The Reshuffle Model",
    author: "Sangeet Paul Choudary",
    description:
      "A strategic framework for aligning organizational culture and leadership with evolving digital technologies. Focuses on platform thinking and ecosystem orchestration.",
    adoptionRate: 78,
    slug: "reshuffle-model",
  },
  {
    id: "fr2",
    name: "The Digital Master Framework",
    author: "George Westerman",
    description:
      "Focused on creating a digital culture across all levels of an organization. Emphasizes the importance of digital leadership and governance structures.",
    adoptionRate: 65,
    slug: "digital-master-framework",
  },
  {
    id: "fr3",
    name: "AI-First Transformation Model",
    author: "MIT Digital Strategy Lab",
    description:
      "A comprehensive approach to building AI capabilities into organizational DNA. Addresses both technical implementation and cultural change management.",
    adoptionRate: 52,
    slug: "ai-first-transformation",
  },
];

// Export all data
export {
  featuredBooks,
  frontierBooks,
  topBooksThisWeek,
  expertReviews,
  brieflyNotedBooks,
  frameworkRankings,
};
